name: Backend CI

on:
  pull_request:
    branches:
      - main
      - dev
      - master
    paths:
      - '../../backend'

jobs:
  run-jest-tests:
    name: Jest Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      # Checkout del código
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Configurar git para HTTP
      - name: Reconfigure git to use HTTP authentication
        run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/

      # NodeJS
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # Copiar .env
      - name: Copy .env.example to .env
        run: cp .env.example .env

      # Setear DATABASE_URL para tests
      - name: Set DATABASE_URL for tests
        run: echo "DATABASE_URL=postgresql://postgres:password@localhost:5432/app" >> $GITHUB_ENV

      - name: Debug env
        run: |
          echo $POSTGRES_DB
          echo $POSTGRES_USER
          echo $POSTGRES_PASSWORD

      # Levantar contenedores con Docker Compose
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./backend/docker-compose.yml
          up-flags: -d

      # Generar Prisma Client
      - name: Prisma Generate
        run: npx prisma generate

      # Migraciones
      - name: Run DB migrations
        run: npm run db:migrate:integration

      # Tests unitarios
      - name: Run Jest Tests
        run: npm run test -- --ci --runInBand

      # Tests de integración
      - name: Run Integration Tests
        run: npx dotenv -e .env.test -- jest --config ./test/jest-int.json --runInBand

      # Limpiar contenedores
      - name: Stop docker-compose
        if: always()
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./backend/docker-compose.yml
          down-flags: -v